name: CD Build and Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v1

      - name: Yarn Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Jest Tests
        run: yarn test:ci

      - name: Typescript build
        run: yarn build

      - name: Set Version to Release Tag Name
        run: |
          yarn version --new-version ${{ github.event.release.tag_name }} --no-git-tag-version

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
